export const SET_HOTELS = 'SET_HOTELS';
export const SET_HOTELS_SUCCESS = 'SET_HOTELS_SUCCESS';
export const GET_HOTELS = 'GET_HOTELS';
export const HOTELS_RECEIVED = 'HOTELS_RECEIVED';
export const UPDATE_HOTELS = 'UPDATE_HOTELS';
export const DELETE_HOTELS = 'DELETE_HOTELS';
export const UPDATE_HOTELS_LIST = 'UPDATE_HOTELS_LIST';
export const GET_HOTEL_DETAILS = 'GET_HOTEL_DETAILS';
export const HOTEL_DETAILS_RECEIVED = 'HOTEL_DETAILS_RECEIVED';
export const GET_CHANNELS = 'GET_CHANNELS'
export const GET_CHANNELS_RECEIVED = 'GET_CHANNELS_RECEIVED';
export const GET_KALTURA_CHANNELS = 'GET_KALTURA_CHANNELS'
export const GET_KALTURA_CHANNELS_RECEIVED = 'GET_KALTURA_CHANNELS_RECEIVED';
export const CONFIG_DEVICES = 'CONFIG_DEVICES';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const DELETE_HOTEL = 'DELETE_HOTEL';
export const DELETE_HOTEL_SUCCESS = 'DELETE_HOTEL_SUCCESS';
export const DELETE_HOTEL_SERIAL_NUMBER = 'DELETE_HOTEL_SERIAL_NUMBER';
export const DELETE_HOTEL_SERIAL_NUMBER_SUCCESS = 'DELETE_HOTEL_SERIAL_NUMBER_SUCCESS';

export const GET_THEMES = 'GET_THEMES';
export const GET_THEMES_SUCCESS = 'GET_THEMES_SUCCESS';

export const HOTEL_ERROR = 'HOTEL_ERROR';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';

export const GET_POSTCODES = 'GET_POSTCODES';
export const GET_POSTCODES_SUCCESS = 'GET_POSTCODES_SUCCESS';

export const REGISTER_DEVICE = 'REGISTER_DEVICE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const GET_HOTELS_WITH_DEVICE_SERIAL_NO = 'GET_HOTELS_WITH_DEVICE_SERIAL_NO';
export const GET_HOTELS_WITH_DEVICE_SERIAL_NO_SUCCESS = 'GET_HOTELS_WITH_DEVICE_SERIAL_NO_SUCCESS';
export const GET_HOTELS_WITH_DEVICE_SERIAL_NO_ERROR = 'GET_HOTELS_WITH_DEVICE_SERIAL_NO_ERROR';
