export const ADD_THIRD_PARTY_SERVICES = 'ADD_THIRD_PARTY_SERVICES';
export const GET_THIRD_PARTY_SERVICES = 'GET_THIRD_PARTY_SERVICES';
export const THIRD_PARTY_SERVICES_RECEIVED = 'THIRD_PARTY_SERVICES_RECEIVED';
export const UPDATE_THIRD_PARTY_SERVICES = 'UPDATE_THIRD_PARTY_SERVICES';
export const DELETE_THIRD_PARTY_SERVICES = 'DELETE_THIRD_PARTY_SERVICES';
export const UPDATE_THIRD_PARTY_SERVICES_LIST = 'UPDATE_THIRD_PARTY_SERVICES_LIST';
export const TPSERROR = 'TPSERROR';
