name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.12.0'

      - name: Install system dependencies
        working-directory: /
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make g++

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Copy build files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          source: /dist/*   # Path to your built files
          target: /home/n/hz-admin-fe1 # Remote directory where files will be copied

      - name: SSH into server and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/remote/directory   # Change directory to where the files are copied
            pm2 restart <your-app-name>    # Restart your application using PM2 or any other tool
